### PR TITLE
fix: InterruptGuard lives not long enough to protect concurrent access

### LINKED ISSUE #11: LockGuard lives not long enough to protect concurrent access
This is follow-up of #10 . More details can be found on https://vojtechkral.github.io/blag/rust-drop-order/.

### PR DESCRIPTION
**Pull request by rust-cooker**
Description: InterruptGuard lives not long enough to protect concurrent access

Reason: use _ the guard returned by lock() is dropped right away on that first line and the lock isn't locked when resource is accessed.

fixes #11

### CODE REVIEW

**Comment by lawkai-vivo** [comment]
This isssue is fixed by #18

**Comment by lawkai-vivo** [comment]
Ok, I see #18 is partial fix.

**Comment by lawkai-vivo** [comment]
Please rebase this PR.

File: kernel/src/scheduler/mod.rs [hunk 1]
```diff
@@ -421,15 +421,15 @@ pub(crate) extern "C" fn schedule() -> ! {
 
 #[inline]
 pub fn current_thread() -> ThreadNode {
-    let _ = DisableInterruptGuard::new();
+    let _dig = DisableInterruptGuard::new();
```
Comment (han-jiang277) [inline kernel/src/scheduler/mod.rs]: _guard is better

Comment (zwbZ) [reply kernel/src/scheduler/mod.rs]: Good suggestion
